// ============================================================================
// SK8 ↔ Base44 connector — configuration selector
// ----------------------------------------------------------------------------
// ONE switch decides where the per-deployment config comes from:
//
//   CONFIG_MODE = "static"       → values are filled into sk8Config.static.js
//                                  (build-time; nothing fetched at runtime)
//   CONFIG_MODE = "integration"  → values are fetched at runtime from the
//                                  "sk8-connector-config" custom integration,
//                                  so they're managed centrally across all apps
//
// The rest of the connector is identical in both modes — it only ever calls
// getSk8Config(). Do NOT edit this file per deployment; edit the chosen provider:
//   • static mode      → sk8Config.static.js  (fill the marked values)
//   • integration mode → nothing to fill (managed in the custom integration)
// ============================================================================
import { loadConfig as loadStatic }      from "./sk8Config.static";
import { loadConfig as loadIntegration } from "./sk8Config.integration";

// ▼▼▼ THE ONLY SWITCH ▼▼▼  ("static" | "integration")
export const CONFIG_MODE = "integration";
// ▲▲▲

export const REDIRECT_PATH = "/oauth/callback";

let _config = null;
export async function getSk8Config() {
  if (_config) return _config;
  const raw = await (CONFIG_MODE === "integration" ? loadIntegration() : loadStatic());
  _config = { ...raw, REDIRECT_PATH };
  return _config;
}
